######################################################################
# Automatically generated by qmake (2.01a) ?? 4? 4 15:06:18 2021
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
