######################################################################
# Automatically generated by qmake (2.01a) ?? 4? 4 15:08:04 2021
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += dialog.h
SOURCES += dialog.cpp main.cpp
